name: 'Teamwork GitHub Sync'
description: 'This action helps you to sync your PRs with tasks in Teamwork to streamline team collaboration and your development workflows.'
branding:
  icon: 'alert-circle'
  color: 'gray-dark'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TEAMWORK_URI:
    description: 'Teamwork URI'
    required: true
  TEAMWORK_API_TOKEN:
    description: 'Teamwork API token'
    required: true
  AUTOMATIC_TAGGING:
    description: 'Do you want to enable automatic tagging: true/false'
    required: false
  BOARD_COLUMN_OPENED:
    description: 'The case-sensitive column name of the column you would like the task to be moved to once the PR has been opened'
    required: false
    default: ''
  BOARD_COLUMN_MERGED:
    description: 'The case-sensitive column name of the column you would like the task to be moved to once the PR has been merged'
    required: false
    default: ''
  BOARD_COLUMN_CLOSED:
    description: 'The case-sensitive column name of the column you would like the task to be moved to if the PR was closed without being merged'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.TEAMWORK_URI }}
    - ${{ inputs.TEAMWORK_API_TOKEN }}
    - ${{ inputs.AUTOMATIC_TAGGING }}
    - ${{ inputs.BOARD_COLUMN_OPENED }}
    - ${{ inputs.BOARD_COLUMN_MERGED }}
    - ${{ inputs.BOARD_COLUMN_CLOSED }}
